#!/bin/sh
set -e
cp -r test* "$AUTOPKGTEST_TMP/" && cd "$AUTOPKGTEST_TMP"
for py in $(py3versions -s); do
    $py -Wd -m pytest -v --asyncio-mode=auto -x -k "not test_single_addr_info_close_errors" 2>&1
done
